name=JWPLC_RS485
version=1.0.1
author=JW Control
maintainer=JW Control <jw.control.peru@gmail.com>
sentence=Puerto RS-485 automático para JWPLC Basic.
paragraph=Librería interna del ecosistema JWPLC para usar Serial2 como puerto RS-485 industrial, con soporte UART genérico, hooks weak para control DE/RE futuro y defaults propios del JWPLC Basic.
category=Communication
url=https://github.com/JW-Control/platform-jwplc
architectures=esp32
