name=JWPLC_Ethernet
version=1.0.0
author=JW Control
maintainer=JW Control
sentence=Ethernet W5500 helper library for JWPLC Basic.
paragraph=Internal JWPLC library for W5500 Ethernet status, DHCP/static IP initialization, link monitoring and Arduino-friendly API.
category=Communication
url=https://github.com/JW-Control/platform-jwplc
architectures=esp32
depends=Ethernet
