name=JWPLC_Display_ST7789
version=1.0.0
author=JW Control
maintainer=JW Control
sentence=Display automatico ST7789 para JWPLC Basic usando los hooks del core JWPLC.
paragraph=Implementa la pantalla base del JWPLC Basic, mostrando entradas, salidas y una zona reservada para RTC sin necesidad de codigo grafico en el sketch.
category=Display
url=https://github.com/JW-Control/platform-jwplc
architectures=esp32
depends=Adafruit GFX Library,Adafruit ST7735 and ST7789 Library,JW_MatrixButtons,JWPLC_GlobalPeripherals