name=JWPLC_GlobalPeripherals
version=1.0.0
author=JW Control
maintainer=JW Control <jw.control.peru@gmail.com>
sentence=Periféricos globales del ecosistema JWPLC.
paragraph=Expone objetos globales reutilizables del ecosistema JWPLC, como RTC, FRAM, microSD, botonera y Ethernet, manteniendo la inicialización automática del package sin crear APIs paralelas innecesarias.
category=Device Control
url=https://github.com/JW-Control/platform-jwplc
architectures=esp32
depends=JW_RTC,JW_FRAM,JW_MatrixButtons,JW_SD,JWPLC_Ethernet,JWPLC_RS485
