name=JWPLC_Display
version=1.0.1
author=JW Control
maintainer=JW Control <jw.control.peru@gmail.com>
sentence=Display ST7789 e HMI declarativa para JWPLC Basic.
paragraph=Implementa la pantalla IDLE/USER del JWPLC Basic, HMI declarativa por campos y paginas, callbacks de usuario, diagnosticos visuales, navegacion coordinada con la botonera global y acceso opcional a la TFT mediante la API JWPLC_Display.
category=Display
url=https://github.com/JW-Control/platform-jwplc
architectures=esp32
precompiled=full
ldflags=-Wl,--undefined=JWPLC_Display
depends=Adafruit GFX Library,Adafruit ST7735 and ST7789 Library,JW_MatrixButtons,JWPLC_GlobalPeripherals
