name=JWPLC_Display
version=1.0.1
author=JW Control
maintainer=JW Control <jw.control.peru@gmail.com>
sentence=Display ST7789 e HMI declarativa para JWPLC Basic.
paragraph=Implementa IDLE/USER, HMI declarativa, navegacion, diagnosticos y acceso grafico JWPLC_TFT sin exponer backends externos.
category=Display
url=https://github.com/JW-Control/platform-jwplc
architectures=esp32
includes=JWPLC_Display.h
dot_a_linkage=true
precompiled=full
depends=JWPLC_TFT,JW_MatrixButtons,JWPLC_GlobalPeripherals