name=JWPLC_Display
version=1.0.1
author=JW Control
maintainer=JW Control <jw.control.peru@gmail.com>
sentence=Display ST7789 automático para JWPLC Basic.
paragraph=Implementa la pantalla IDLE/USER del JWPLC Basic, callbacks de usuario, botonera integrada, LEDs de estado y acceso opcional a la TFT mediante la API JWPLC_Display.
category=Display
url=https://github.com/JW-Control/platform-jwplc
architectures=esp32
depends=Adafruit GFX Library,Adafruit ST7735 and ST7789 Library,JW_MatrixButtons,JWPLC_GlobalPeripherals
