name=JWPLC_LogicRuntime_UI
version=0.5.7
sentence=Interfaz USER modular para JWPLC Logic Runtime.
paragraph=Conecta los motores lógicos v1 y v2 con la TFT y la botonera del JWPLC Basic, incluyendo mapa FBD con refresco regional, bloque virtual de creación no invasivo, selección de tipo sin parpadeo y mini mapa contextual con fila/columna para configurar fuentes reales sin escribir FRAM.
category=Display
url=https://github.com/JW-Control/platform-jwplc
architectures=esp32
depends=JWPLC_LogicRuntime,JWPLC_Display,JWPLC_GlobalPeripherals
