name=JW_FRAM
version=1.0.2
author=JW Control
maintainer=JW Control
sentence=Libreria SPI FRAM con API estilo EEPROM para ESP32.
paragraph=Incluye acceso de bajo nivel y alto nivel para FRAM SPI, con soporte para tipos numericos, String, C strings, structs y bloques validados.
category=Data Storage
url=https://github.com/JW-Control/JW_FRAM
architectures=esp32
depends=Adafruit BusIO
